### ISSUE TITLE
抓取各地区Bing搜索首页的背景图 - Lumos Maximum

### ISSUE THREAD

**Issue by LemonPrefect** [LemonPrefect/BlogComment#3]
https://lemonprefect.cn/2019/12/15/%E6%8A%93%E5%8F%96%E5%90%84%E5%9C%B0%E5%8C%BAbing%E6%90%9C%E7%B4%A2%E9%A6%96%E9%A1%B5%E7%9A%84%E8%83%8C%E6%99%AF%E5%9B%BE/ 

 Bing的限定从去年开始，Bing就开始对访问搜索首页的IP进行判别然后显示对应地区的背景图，因此，原来单纯使用 cc 这一请求参数来混淆地区以获取不同地区的背景图的方法失效了。于是便试着通过构造一个含有x-forwarded-for的请求头。

**Comment by livefordead** [comment]
ohhhhh
